#!/usr/bin/env node
/**
 * Pack contract: training + live city minimum sets (M3a).
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

function fail(msg) {
  console.error(`validate:packs FAIL — ${msg}`)
  process.exitCode = 1
}

function readJson(p) {
  return JSON.parse(fs.readFileSync(p, 'utf8'))
}

function packDir(id) {
  const a = path.join(root, 'public', 'packs', id)
  if (fs.existsSync(a)) return a
  return path.join(root, 'packs', id)
}

function questionsFor(quiz, band) {
  return (quiz.questions ?? []).filter(
    (q) => q.ageBand === band || (Array.isArray(q.ageBands) && q.ageBands.includes(band)),
  )
}

const manifestPath = path.join(root, 'public', 'packs', 'manifest.json')
if (!fs.existsSync(manifestPath)) fail('missing public/packs/manifest.json')
const manifest = readJson(manifestPath)
const ids = (manifest.packs ?? []).map((p) => p.id)
if (!ids.includes('xingwan-training')) fail('manifest missing xingwan-training')
for (const need of ['beijing', 'shanghai', 'harbin', 'guangzhou', 'wuhan', 'chengdu', 'xian']) {
  if (!ids.includes(need)) fail(`manifest missing ${need}`)
}

const liveCity = (manifest.liveCityPacks ?? []).filter(Boolean)
if (liveCity.length < 7) fail(`liveCityPacks ${liveCity.length} < 7`)
for (const need of ['beijing', 'shanghai', 'harbin', 'guangzhou', 'wuhan', 'chengdu', 'xian']) {
  if (!liveCity.includes(need)) fail(`liveCityPacks missing ${need}`)
}

const xwDir = packDir('xingwan-training')
for (const f of ['city.json', 'layout.json', 'quiz.json', 'knowledge.json']) {
  if (!fs.existsSync(path.join(xwDir, f))) fail(`missing ${xwDir}/${f}`)
}
const xw = readJson(path.join(xwDir, 'city.json'))
if (!xw.fictional && xw.unitType !== 'training') fail('xingwan must be marked fictional/training')

const cityRules = {
  beijing: {
    minZones: 4,
    minLandmarks: 5,
    guardName: /天安门/,
    visitName: /故宫/,
    themes: ['首都', '京', '温带季风', '胡同', '中轴'],
    modifiers: ['hutong_maze', 'axis_guard'],
    adcode: '110100',
    region7: '华北',
  },
  shanghai: {
    minZones: 4,
    minLandmarks: 5,
    guardName: /纪念碑/,
    visitName: /外滩/,
    themes: ['沪', '黄浦江', '亚热带季风', '里弄'],
    modifiers: ['river_front'],
    adcode: '310100',
    region7: '华东',
  },
  harbin: {
    minZones: 4,
    minLandmarks: 5,
    guardName: /防洪/,
    visitName: /索菲亚|教堂/,
    themes: ['黑', '松花江', '冰雪'],
    modifiers: ['cold_wide_street'],
    adcode: '230100',
    region7: '东北',
  },
  guangzhou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /陈家祠|镇海|骑楼/,
    themes: ['粤', '珠江', '骑楼', '亚热带'],
    modifiers: ['qilou_arcade'],
    adcode: '440100',
    region7: '华南',
  },
  wuhan: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /防汛|纪念|抗洪/,
    visitName: /黄鹤/,
    themes: ['鄂', '长江', '汉江', '两江'],
    modifiers: ['two_rivers_confluence'],
    adcode: '420100',
    region7: '华中',
  },
  chengdu: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /武侯|宽窄/,
    themes: ['川', '天府', '盆地', '都江堰'],
    modifiers: ['basin_fog'],
    adcode: '510100',
    region7: '西南',
  },
  xian: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /雁塔|城墙/,
    themes: ['陕', '渭河', '古都', '丝路'],
    modifiers: ['citywall_ring'],
    adcode: '610100',
    region7: '西北',
  },
  baoding: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /总督署|莲花/,
    themes: ['冀', '保定', '温带季风', '府河'],
    modifiers: ['hutong_maze'],
    adcode: '130600',
    region7: '华北',
  },
  shenyang: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /九一八|纪念/,
    visitName: /故宫/,
    themes: ['辽', '浑河', '沈阳'],
    modifiers: ['cold_wide_street'],
    adcode: '210100',
    region7: '东北',
  },
  dalian: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /中山|广场/,
    themes: ['辽', '大连', '黄海', '港口'],
    modifiers: ['coastal_band'],
    adcode: '210200',
    region7: '东北',
  },
  suzhou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /拙政|寒山/,
    themes: ['苏', '苏州', '大运河', '太湖'],
    modifiers: ['river_front'],
    adcode: '320500',
    region7: '华东',
  },
  luoyang: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /龙门|白马/,
    themes: ['豫', '洛阳', '洛河', '古都'],
    modifiers: ['named_river'],
    adcode: '410300',
    region7: '华中',
  },
  shenzhen: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /大鹏|天后/,
    themes: ['粤', '深圳', '经济特区', '亚热带'],
    modifiers: ['qilou_arcade'],
    adcode: '440300',
    region7: '华南',
  },
  kunming: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /金马|滇池|金殿/,
    themes: ['云', '昆明', '滇池', '春城'],
    modifiers: ['plateau_lake'],
    adcode: '530100',
    region7: '西南',
  },
  zunyi: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /红军|纪念/,
    visitName: /会议会址|会址/,
    themes: ['贵', '遵义', '黔北'],
    modifiers: ['named_river'],
    adcode: '520300',
    region7: '西南',
  },
  jiuquan: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /莫高|鼓楼/,
    themes: ['甘', '酒泉', '河西走廊', '绿洲'],
    modifiers: ['oasis_canal'],
    adcode: '620900',
    region7: '西北',
  },
  tangshan: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /开滦|南湖|矿山/,
    themes: ['冀', '唐山', '渤海', '温带季风'],
    modifiers: ['coastal_band'],
    adcode: '130200',
    region7: '华北',
  },
  handan: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /丛台/,
    themes: ['冀', '邯郸', '滏阳河', '温带季风'],
    modifiers: ['named_river'],
    adcode: '130400',
    region7: '华北',
  },
  jilin: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /北山|江岸/,
    themes: ['吉', '吉林', '松花江', '长春'],
    modifiers: ['named_river'],
    adcode: '220200',
    region7: '东北',
  },
  qiqihar: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /龙沙|扎龙/,
    themes: ['黑', '齐齐哈尔', '嫩江'],
    modifiers: ['named_river'],
    adcode: '230200',
    region7: '东北',
  },
  qingdao: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /栈桥|教堂/,
    themes: ['鲁', '青岛', '黄海', '温带季风'],
    modifiers: ['coastal_band'],
    adcode: '370200',
    region7: '华东',
  },
  wuxi: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /寄畅|南禅|太湖/,
    themes: ['苏', '无锡', '太湖', '大运河'],
    modifiers: ['river_front'],
    adcode: '320200',
    region7: '华东',
  },
  kaifeng: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /铁塔|相国/,
    themes: ['豫', '开封', '黄河', '古都'],
    modifiers: ['named_river'],
    adcode: '410200',
    region7: '华中',
  },
  xiangyang: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /城墙|汉江/,
    themes: ['鄂', '襄阳', '汉江'],
    modifiers: ['named_river'],
    adcode: '420600',
    region7: '华中',
  },
  guilin: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /王城|漓江/,
    themes: ['桂', '桂林', '漓江', '喀斯特'],
    modifiers: ['named_river'],
    adcode: '450300',
    region7: '华南',
  },
  foshan: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /祖庙|骑楼/,
    themes: ['粤', '佛山', '珠江三角洲', '骑楼'],
    modifiers: ['qilou_arcade'],
    adcode: '440600',
    region7: '华南',
  },
  leshan: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /大佛/,
    themes: ['川', '乐山', '岷江', '大佛'],
    modifiers: ['named_river'],
    adcode: '511100',
    region7: '西南',
  },
  mianyang: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /子云|涪江/,
    themes: ['川', '绵阳', '涪江'],
    modifiers: ['named_river'],
    adcode: '510700',
    region7: '西南',
  },
  baoji: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /金台|青铜|渭河/,
    themes: ['陕', '宝鸡', '渭河', '关中'],
    modifiers: ['named_river'],
    adcode: '610300',
    region7: '西北',
  },
  xianyang: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /城墙|渭河/,
    themes: ['陕', '咸阳', '渭河', '非省会'],
    modifiers: ['named_river'],
    adcode: '610400',
    region7: '西北',
  },
  shijiazhuang: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /隆兴|正定|滹沱/,
    themes: ['冀', '石家庄', '滹沱河'],
    modifiers: ['named_river'],
    adcode: '130100',
    region7: '华北',
  },
  changchun: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /南湖|文庙/,
    themes: ['吉', '长春', '伊通河'],
    modifiers: ['cold_wide_street'],
    adcode: '220100',
    region7: '东北',
  },
  changsha: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /岳麓/,
    themes: ['湘', '长沙', '湘江'],
    modifiers: ['named_river'],
    adcode: '430100',
    region7: '华中',
  },
  guiyang: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /甲秀/,
    themes: ['贵', '贵阳', '南明河'],
    modifiers: ['named_river'],
    adcode: '520100',
    region7: '西南',
  },
  urumqi: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /红山|巴扎/,
    themes: ['新', '乌鲁木齐', '天山', '绿洲'],
    modifiers: ['oasis_canal'],
    adcode: '650100',
    region7: '西北',
  },
  tianjin: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /五大道|海河|古文化/,
    themes: ['津', '天津', '海河'],
    modifiers: ['coastal_band'],
    adcode: '120100',
    region7: '华北',
  },
  taiyuan: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /晋祠/,
    themes: ['晋', '太原', '汾河'],
    modifiers: ['named_river'],
    adcode: '140100',
    region7: '华北',
  },
  hohhot: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /大召/,
    themes: ['内蒙古', '呼和浩特'],
    modifiers: ['named_river'],
    adcode: '150100',
    region7: '华北',
  },
  nanjing: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念|雨花/,
    visitName: /夫子|城墙/,
    themes: ['苏', '南京', '长江'],
    modifiers: ['river_front'],
    adcode: '320100',
    region7: '华东',
  },
  hangzhou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /西湖|断桥|灵隐/,
    themes: ['浙', '杭州', '西湖'],
    modifiers: ['river_front'],
    adcode: '330100',
    region7: '华东',
  },
  hefei: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念|渡江/,
    visitName: /包公/,
    themes: ['皖', '合肥', '巢湖'],
    modifiers: ['named_river'],
    adcode: '340100',
    region7: '华东',
  },
  fuzhou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /三坊七巷/,
    themes: ['闽', '福州', '闽江'],
    modifiers: ['river_front'],
    adcode: '350100',
    region7: '华东',
  },
  nanchang: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /八一|纪念/,
    visitName: /滕王/,
    themes: ['赣', '南昌', '赣江'],
    modifiers: ['named_river'],
    adcode: '360100',
    region7: '华东',
  },
  jinan: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /趵突|大明湖/,
    themes: ['鲁', '济南', '泉'],
    modifiers: ['named_river'],
    adcode: '370100',
    region7: '华东',
  },
  zhengzhou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /商都|黄河/,
    themes: ['豫', '郑州', '黄河'],
    modifiers: ['named_river'],
    adcode: '410100',
    region7: '华中',
  },
  nanning: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /骑楼|邕江/,
    themes: ['桂', '南宁'],
    modifiers: ['qilou_arcade'],
    adcode: '450100',
    region7: '华南',
  },
  haikou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /骑楼|海岸/,
    themes: ['琼', '海口'],
    modifiers: ['qilou_arcade'],
    adcode: '460100',
    region7: '华南',
  },
  chongqing: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /解放|纪念/,
    visitName: /湖广|两江/,
    themes: ['渝', '重庆', '长江', '嘉陵'],
    modifiers: ['two_rivers_confluence'],
    adcode: '500100',
    region7: '西南',
  },
  lhasa: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /布达拉|大昭/,
    themes: ['藏', '拉萨', '拉萨河'],
    modifiers: ['named_river'],
    adcode: '540100',
    region7: '西南',
  },
  lanzhou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /铁桥|黄河/,
    themes: ['甘', '兰州', '黄河'],
    modifiers: ['named_river'],
    adcode: '620100',
    region7: '西北',
  },
  xining: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /东关|湟水/,
    themes: ['青', '西宁'],
    modifiers: ['named_river'],
    adcode: '630100',
    region7: '西北',
  },
  yinchuan: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /海宝/,
    themes: ['宁', '银川', '黄河'],
    modifiers: ['oasis_canal'],
    adcode: '640100',
    region7: '西北',
  },
  taipei: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /北门|龙山|故宫/,
    themes: ['台', '台北', '淡水河', '教学'],
    modifiers: ['named_river'],
    adcode: '710100',
    region7: '华东',
  },
  hongkong: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /金紫荆|纪念/,
    visitName: /太平山|大馆/,
    themes: ['港', '香港', '特别行政区'],
    modifiers: ['qilou_arcade'],
    adcode: '810100',
    region7: '华南',
  },
  macau: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /金莲花|纪念/,
    visitName: /大三巴|妈阁/,
    themes: ['澳', '澳门', '特别行政区'],
    modifiers: ['qilou_arcade'],
    adcode: '820100',
    region7: '华南',
  },
  datong: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /云冈/,
    themes: ['晋', '大同', '御河'],
    modifiers: ['named_river'],
    adcode: '140200',
    region7: '华北',
  },
  baotou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /五当召|黄河/,
    themes: ['内蒙古', '包头', '黄河'],
    modifiers: ['named_river'],
    adcode: '150200',
    region7: '华北',
  },
  ningbo: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /天一阁|甬江/,
    themes: ['浙', '宁波', '东海'],
    modifiers: ['coastal_band'],
    adcode: '330200',
    region7: '华东',
  },
  wuhu: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /广济|长江/,
    themes: ['皖', '芜湖', '长江'],
    modifiers: ['named_river'],
    adcode: '340200',
    region7: '华东',
  },
  xiamen: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /南普陀|骑楼|海峡/,
    themes: ['闽', '厦门', '海峡'],
    modifiers: ['qilou_arcade'],
    adcode: '350200',
    region7: '华东',
  },
  jingdezhen: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /御窑|昌江/,
    themes: ['赣', '景德镇', '昌江'],
    modifiers: ['named_river'],
    adcode: '360200',
    region7: '华东',
  },
  zhuzhou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /神农|湘江/,
    themes: ['湘', '株洲', '湘江'],
    modifiers: ['named_river'],
    adcode: '430200',
    region7: '华中',
  },
  sanya: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /南山|南海|骑楼/,
    themes: ['琼', '三亚', '南海'],
    modifiers: ['coastal_band'],
    adcode: '460200',
    region7: '华南',
  },
  qujing: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /文庙|南盘江/,
    themes: ['云', '曲靖', '南盘江'],
    modifiers: ['named_river'],
    adcode: '530300',
    region7: '西南',
  },
  shigatse: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /扎什伦布|年楚|雅鲁藏布/,
    themes: ['藏', '日喀则', '雅鲁藏布江'],
    modifiers: ['named_river'],
    adcode: '540200',
    region7: '西南',
  },
  haidong: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /瞿昙|湟水/,
    themes: ['青', '海东', '湟水'],
    modifiers: ['named_river'],
    adcode: '630200',
    region7: '西北',
  },
  shizuishan: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /武当|黄河/,
    themes: ['宁', '石嘴山', '黄河'],
    modifiers: ['oasis_canal'],
    adcode: '640200',
    region7: '西北',
  },
  kelamayi: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /工业遗产|水渠|绿洲/,
    themes: ['新', '克拉玛依', '绿洲'],
    modifiers: ['oasis_canal'],
    adcode: '650200',
    region7: '西北',
  },
  yuncheng: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /关帝|盐池|涑水/,
    themes: ['晋', '运城', '盐池'],
    modifiers: ['named_river'],
    adcode: '140800',
    region7: '华北',
  },
  chifeng: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /红山|西辽河/,
    themes: ['内蒙古', '赤峰', '西辽河'],
    modifiers: ['named_river'],
    adcode: '150400',
    region7: '华北',
  },
  dandong: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /鸭绿|断桥/,
    themes: ['辽', '丹东', '鸭绿江'],
    modifiers: ['named_river'],
    adcode: '210600',
    region7: '东北',
  },
  songyuan: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /松花|古庙/,
    themes: ['吉', '松原', '松嫩平原'],
    modifiers: ['named_river'],
    adcode: '220700',
    region7: '东北',
  },
  daqing: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /工业遗产|湿地/,
    themes: ['黑', '大庆', '松嫩平原'],
    modifiers: ['named_river'],
    adcode: '230600',
    region7: '东北',
  },
  shaoxing: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /兰亭|运河|鉴湖/,
    themes: ['浙', '绍兴', '鉴湖'],
    modifiers: ['named_river'],
    adcode: '330600',
    region7: '华东',
  },
  bengbu: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /禹王|淮河/,
    themes: ['皖', '蚌埠', '淮河'],
    modifiers: ['named_river'],
    adcode: '340300',
    region7: '华东',
  },
  quanzhou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /开元|晋江|骑楼/,
    themes: ['闽', '泉州', '晋江'],
    modifiers: ['qilou_arcade'],
    adcode: '350500',
    region7: '华东',
  },
  jiujiang: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /锁江|长江|鄱阳/,
    themes: ['赣', '九江', '鄱阳湖'],
    modifiers: ['named_river'],
    adcode: '360400',
    region7: '华东',
  },
  dongying: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /黄河|湿地/,
    themes: ['鲁', '东营', '黄河'],
    modifiers: ['named_river'],
    adcode: '370500',
    region7: '华东',
  },
  jingzhou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /城墙|长江/,
    themes: ['鄂', '荆州', '长江'],
    modifiers: ['named_river'],
    adcode: '421000',
    region7: '华中',
  },
  yueyang: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /岳阳楼|洞庭/,
    themes: ['湘', '岳阳', '洞庭湖'],
    modifiers: ['named_river'],
    adcode: '430600',
    region7: '华中',
  },
  beihai: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /骑楼|北部湾/,
    themes: ['桂', '北海', '北部湾'],
    modifiers: ['qilou_arcade'],
    adcode: '450500',
    region7: '华南',
  },
  danzhou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /东坡|书院|北部湾/,
    themes: ['琼', '儋州', '北部湾'],
    modifiers: ['qilou_arcade'],
    adcode: '460400',
    region7: '华南',
  },
  liupanshui: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /水城|北盘江/,
    themes: ['贵', '六盘水', '北盘江'],
    modifiers: ['named_river'],
    adcode: '520200',
    region7: '西南',
  },
  yuxi: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /文庙|抚仙/,
    themes: ['云', '玉溪', '抚仙湖'],
    modifiers: ['named_river'],
    adcode: '530400',
    region7: '西南',
  },
  shannan: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /昌珠|雅砻|雅鲁藏布/,
    themes: ['藏', '山南', '雅鲁藏布江'],
    modifiers: ['named_river'],
    adcode: '540500',
    region7: '西南',
  },
  tianshui: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /麦积|渭河/,
    themes: ['甘', '天水', '渭河'],
    modifiers: ['named_river'],
    adcode: '620500',
    region7: '西北',
  },
  wuzhong: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /董府|黄河|秦渠/,
    themes: ['宁', '吴忠', '黄河'],
    modifiers: ['oasis_canal'],
    adcode: '640300',
    region7: '西北',
  },
  tulufan: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /苏公|坎儿井/,
    themes: ['新', '吐鲁番', '坎儿井'],
    modifiers: ['oasis_canal'],
    adcode: '650400',
    region7: '西北',
  },
  linfen: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /尧庙|汾河/,
    themes: ['晋', '临汾', '汾河'],
    modifiers: ['named_river'],
    adcode: '141000',
    region7: '华北',
  },
  tongliao: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /文庙|西辽河/,
    themes: ['内蒙古', '通辽', '西辽河'],
    modifiers: ['named_river'],
    adcode: '150500',
    region7: '华北',
  },
  panjin: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /湿地|辽河/,
    themes: ['辽', '盘锦', '辽河'],
    modifiers: ['named_river'],
    adcode: '211100',
    region7: '东北',
  },
  siping: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /文庙|东辽河|辽河平原/,
    themes: ['吉', '四平', '辽河平原'],
    modifiers: ['named_river'],
    adcode: '220300',
    region7: '东北',
  },
  jiamusi: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /古庙|松花|三江/,
    themes: ['黑', '佳木斯', '三江平原'],
    modifiers: ['named_river'],
    adcode: '230800',
    region7: '东北',
  },
  yangzhou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /个园|运河/,
    themes: ['苏', '扬州', '京杭运河'],
    modifiers: ['named_river'],
    adcode: '321000',
    region7: '华东',
  },
  jiaxing: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /烟雨|南湖|运河/,
    themes: ['浙', '嘉兴', '南湖'],
    modifiers: ['named_river'],
    adcode: '330400',
    region7: '华东',
  },
  anqing: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /迎江|长江/,
    themes: ['皖', '安庆', '长江'],
    modifiers: ['named_river'],
    adcode: '340800',
    region7: '华东',
  },
  zhangzhou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /南山|九龙|骑楼/,
    themes: ['闽', '漳州', '九龙江'],
    modifiers: ['qilou_arcade'],
    adcode: '350600',
    region7: '华东',
  },
  ganzhou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /八境|赣江/,
    themes: ['赣', '赣州', '赣江'],
    modifiers: ['named_river'],
    adcode: '360700',
    region7: '华东',
  },
  jining: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /孔庙|运河|微山/,
    themes: ['鲁', '济宁', '微山湖'],
    modifiers: ['named_river'],
    adcode: '370800',
    region7: '华东',
  },
  anyang: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /殷墟|洹河/,
    themes: ['豫', '安阳', '殷墟'],
    modifiers: ['named_river'],
    adcode: '410500',
    region7: '华中',
  },
  yichang: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /镇江|长江/,
    themes: ['鄂', '宜昌', '长江'],
    modifiers: ['named_river'],
    adcode: '420500',
    region7: '华中',
  },
  hengyang: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /石鼓|湘江/,
    themes: ['湘', '衡阳', '湘江'],
    modifiers: ['named_river'],
    adcode: '430400',
    region7: '华中',
  },
  zhanjiang: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /骑楼|南海|霞山/,
    themes: ['粤', '湛江', '南海'],
    modifiers: ['qilou_arcade'],
    adcode: '440800',
    region7: '华南',
  },
  liuzhou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /东门|柳江/,
    themes: ['桂', '柳州', '柳江'],
    modifiers: ['named_river'],
    adcode: '450200',
    region7: '华南',
  },
  yibin: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /大观|长江|三江/,
    themes: ['川', '宜宾', '长江'],
    modifiers: ['named_river'],
    adcode: '511500',
    region7: '西南',
  },
  tongren: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /东山|锦江/,
    themes: ['贵', '铜仁', '锦江'],
    modifiers: ['named_river'],
    adcode: '520600',
    region7: '西南',
  },
  zhaotong: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /文庙|金沙/,
    themes: ['云', '昭通', '金沙江'],
    modifiers: ['named_river'],
    adcode: '530600',
    region7: '西南',
  },
  changdu: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /强巴|澜沧/,
    themes: ['藏', '昌都', '澜沧江'],
    modifiers: ['named_river'],
    adcode: '540300',
    region7: '西南',
  },
  hanzhong: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /古汉|汉江/,
    themes: ['陕', '汉中', '汉江'],
    modifiers: ['named_river'],
    adcode: '610700',
    region7: '西北',
  },
  zhangye: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /鼓楼|黑河/,
    themes: ['甘', '张掖', '黑河'],
    modifiers: ['oasis_canal'],
    adcode: '620700',
    region7: '西北',
  },
  zhongwei: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /高庙|黄河/,
    themes: ['宁', '中卫', '黄河'],
    modifiers: ['oasis_canal'],
    adcode: '640500',
    region7: '西北',
  },
  hami: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /回王|绿洲|渠/,
    themes: ['新', '哈密', '哈密盆地'],
    modifiers: ['oasis_canal'],
    adcode: '650500',
    region7: '西北',
  },
  qinhuangdao: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /山海关|渤海/,
    themes: ['冀', '秦皇岛', '渤海'],
    modifiers: ['coastal_band'],
    adcode: '130300',
    region7: '华北',
  },
  changzhi: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /城隍|浊漳/,
    themes: ['晋', '长治', '浊漳河'],
    modifiers: ['named_river'],
    adcode: '140400',
    region7: '华北',
  },
  bayannur: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /河套|水闸|黄河/,
    themes: ['内蒙古', '巴彦淖尔', '河套'],
    modifiers: ['oasis_canal'],
    adcode: '150800',
    region7: '华北',
  },
  jinzhou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /广济|小凌|渤海/,
    themes: ['辽', '锦州', '渤海'],
    modifiers: ['named_river'],
    adcode: '210700',
    region7: '东北',
  },
  baicheng: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /古庙|嫩江/,
    themes: ['吉', '白城', '嫩江'],
    modifiers: ['named_river'],
    adcode: '220800',
    region7: '东北',
  },
  heihe: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /瑷珲|黑龙江/,
    themes: ['黑', '黑河', '黑龙江'],
    modifiers: ['named_river'],
    adcode: '231100',
    region7: '东北',
  },
  nantong: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /天宁|濠河|长江/,
    themes: ['苏', '南通', '长江'],
    modifiers: ['named_river'],
    adcode: '320600',
    region7: '华东',
  },
  wenzhou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /江心|瓯江/,
    themes: ['浙', '温州', '瓯江'],
    modifiers: ['named_river'],
    adcode: '330300',
    region7: '华东',
  },
  fuyang: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /文峰|颍河|淮河/,
    themes: ['皖', '阜阳', '颍河'],
    modifiers: ['named_river'],
    adcode: '341200',
    region7: '华东',
  },
  ningde: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /霍童|三都|骑楼/,
    themes: ['闽', '宁德', '三都澳'],
    modifiers: ['qilou_arcade'],
    adcode: '350900',
    region7: '华东',
  },
  jian: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /白鹭|赣江/,
    themes: ['赣', '吉安', '赣江'],
    modifiers: ['named_river'],
    adcode: '360800',
    region7: '华东',
  },
  yantai: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /灯塔|黄海|渤海/,
    themes: ['鲁', '烟台', '胶东半岛'],
    modifiers: ['coastal_band'],
    adcode: '370600',
    region7: '华东',
  },
  xinyang: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /文庙|淮河|浉河/,
    themes: ['豫', '信阳', '淮河'],
    modifiers: ['named_river'],
    adcode: '411500',
    region7: '华中',
  },
  huanggang: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /赤壁|长江/,
    themes: ['鄂', '黄冈', '长江'],
    modifiers: ['named_river'],
    adcode: '421100',
    region7: '华中',
  },
  changde: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /诗墙|沅江|洞庭/,
    themes: ['湘', '常德', '沅江'],
    modifiers: ['named_river'],
    adcode: '430700',
    region7: '华中',
  },
  shantou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /骑楼|韩江|南海/,
    themes: ['粤', '汕头', '韩江'],
    modifiers: ['qilou_arcade'],
    adcode: '440500',
    region7: '华南',
  },
  wuzhou: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /龙母|西江/,
    themes: ['桂', '梧州', '西江'],
    modifiers: ['named_river'],
    adcode: '450400',
    region7: '华南',
  },
  nanchong: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /万卷|嘉陵/,
    themes: ['川', '南充', '嘉陵江'],
    modifiers: ['named_river'],
    adcode: '511300',
    region7: '西南',
  },
  bijie: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /七星|乌江/,
    themes: ['贵', '毕节', '乌江'],
    modifiers: ['named_river'],
    adcode: '520500',
    region7: '西南',
  },
  puer: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /茶马|澜沧/,
    themes: ['云', '普洱', '澜沧江'],
    modifiers: ['named_river'],
    adcode: '530800',
    region7: '西南',
  },
  naqu: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /孝登|羌塘|渠/,
    themes: ['藏', '那曲', '羌塘'],
    modifiers: ['named_river'],
    adcode: '540600',
    region7: '西南',
  },
  yanan: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /宝塔|延河/,
    themes: ['陕', '延安', '延河'],
    modifiers: ['named_river'],
    adcode: '610600',
    region7: '西北',
  },
  longnan: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /文庙|嘉陵/,
    themes: ['甘', '陇南', '嘉陵江'],
    modifiers: ['named_river'],
    adcode: '621200',
    region7: '西北',
  },
  guyuan: {
    minZones: 3,
    minLandmarks: 5,
    guardName: /纪念/,
    visitName: /文庙|清水/,
    themes: ['宁', '固原', '清水河'],
    modifiers: ['named_river'],
    adcode: '640400',
    region7: '西北',
  },
}

for (const id of liveCity) {
  const dir = packDir(id)
  for (const f of ['city.json', 'layout.json', 'quiz.json', 'knowledge.json']) {
    if (!fs.existsSync(path.join(dir, f))) fail(`missing ${dir}/${f}`)
  }
  const city = readJson(path.join(dir, 'city.json'))
  const layout = readJson(path.join(dir, 'layout.json'))
  const quiz = readJson(path.join(dir, 'quiz.json'))
  const knowledge = readJson(path.join(dir, 'knowledge.json'))
  const rule = cityRules[id]

  if (city.fictional) fail(`${id} must not be fictional`)
  if (city.draft) fail(`${id} live pack must not set draft`)
  if (['lat', 'lon', 'latitude', 'longitude'].some((k) => k in city)) fail(`${id} city.json has coords`)
  if (!city.region7) fail(`${id} missing region7`)
  if (rule?.region7 && city.region7 !== rule.region7) fail(`${id} region7 ${city.region7} ≠ ${rule.region7}`)
  if (rule && city.adcode !== rule.adcode) fail(`${id} adcode ${city.adcode} ≠ ${rule.adcode}`)
  if ((layout.zones ?? []).length < (rule?.minZones ?? 3)) fail(`${id} zones ${layout.zones?.length} < ${rule?.minZones ?? 3}`)
  const lms = layout.landmarks ?? city.landmarks ?? []
  if (lms.length < (rule?.minLandmarks ?? 5)) fail(`${id} landmarks ${lms.length} < 5`)
  const interacts = new Set(lms.map((l) => l.interact))
  if (!interacts.has('guard')) fail(`${id} missing interact=guard`)
  if (!interacts.has('visit')) fail(`${id} missing interact=visit`)
  if (rule?.guardName) {
    const g = lms.find((l) => rule.guardName.test(l.name) || rule.guardName.test(l.id))
    if (!g || g.interact !== 'guard') fail(`${id} GUARD landmark missing (${rule.guardName})`)
  }
  if (rule?.visitName) {
    const v = lms.find((l) => rule.visitName.test(l.name) || rule.visitName.test(l.id))
    if (!v || v.interact !== 'visit') fail(`${id} VISIT landmark missing (${rule.visitName})`)
  }
  const cards = knowledge.cards ?? []
  if (cards.length < 8) fail(`${id} knowledge cards ${cards.length} < 8`)
  const blob = JSON.stringify(knowledge)
  for (const need of rule?.themes ?? []) {
    if (!blob.includes(need)) fail(`${id} knowledge missing theme ${need}`)
  }
  const q912 = questionsFor(quiz, '9-12')
  const q68 = questionsFor(quiz, '6-8')
  if (q912.length < 5) fail(`${id} 9-12 quiz ${q912.length} < 5`)
  if (q68.length < 4) fail(`${id} 6-8 quiz ${q68.length} < 4`)
  const mods = city.gameplayModifiers ?? layout.variants ?? []
  if (rule?.modifiers?.length) {
    const ok = rule.modifiers.some((m) => mods.includes(m))
    if (!ok) fail(`${id} needs modifier ${rule.modifiers.join('|')}`)
  }
}

if (process.exitCode) process.exit(process.exitCode)
console.log(`validate:packs OK — training + live cities: ${liveCity.join(', ')}`)
